### ISSUE TITLE
CORS Policy issue

### ISSUE THREAD

**Issue by marymarywan** [marymarywan/React-js-simple#1]
'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by marymarywan** [comment]
app.use((req, res, next) => {
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "POST, GET, PUT");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type");
  next();
})

**Comment by marymarywan** [comment]
install cors and use it in index.js

1. npm install cors 
2. app.use(cors());

**Comment by Chaitanya-Shahare** [comment]
Can you assign this to me?

**Comment by Aryashakya** [comment]
Hi, I would like to work on this issue.

**Comment by marymarywan** [comment]
Sorry, I can solve it now as I posted in a comment - thanks anyway
