### ISSUE TITLE
Each child in a list should have a unique "key" prop.

### ISSUE THREAD

**Issue by marymarywan** [marymarywan/React-js-simple#2]

**Comment by marymarywan** [comment]
`
              response.map((data) =>(
                    <tr>
                        <th scope="row" key={data.id}>{data.id}</th>
                        <td key={data.id}>{data.name}</td>
                        <td key={data.id}>{data.address}</td>
                        <td key={data.id}>{data.post}</td>
                        <td key={data.id}>{data.phone}</td>
                        <td key={data.id}>{data.fax}</td>
                        <td key={data.id}>{data.email}</td>
                    </tr>
                ))
            }`

**Comment by marymarywan** [comment]
`
                response.map((data) =>(
                    <tr>
                        <th scope="row" key={data.id}>{data.id}</th>
                        <td key={data.id}>{data.name}</td>
                        <td key={data.id}>{data.address}</td>
                        <td key={data.id}>{data.post}</td>
                        <td key={data.id}>{data.phone}</td>
                        <td key={data.id}>{data.fax}</td>
                        <td key={data.id}>{data.email}</td>
                    </tr>
                ))
            }`

add a unique key to each children

**Comment by marymarywan** [comment]
> ` response.map((data) =>( <tr> <th scope="row" key={data.id}>{data.id}</th> <td key={data.id}>{data.name}</td> <td key={data.id}>{data.address}</td> <td key={data.id}>{data.post}</td> <td key={data.id}>{data.phone}</td> <td key={data.id}>{data.fax}</td> <td key={data.id}>{data.email}</td> </tr> )) }`
> 
> add a unique key to each children

here is {data.id}

**Comment by Chaitanya-Shahare** [comment]
Can you assign this to me?
